export default [
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 218,
            top: 44,
            left: 17,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 232,
            top: 70,
            left: 0,
            zIndex: 3,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 240,
            top: 2,
            left: 45,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 187,
            top: 13,
            left: 75,
            zIndex: 0,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 269,
            top: 60,
            left: 70,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 230,
            top: 12,
            left: 2,
            zIndex: 0,
        },
        {
            startIndex: 900,
            numImages: 150,
            duration: 3,
            size: 252,
            top: 140,
            left: 40,
            zIndex: 2,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 202,
            top: 10,
            left: 6,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 230,
            top: -3,
            left: 64,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 212,
            top: 60,
            left: 56,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 182,
            top: 75,
            left: 11,
            zIndex: 6,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 190,
            top: 42,
            left: 78,
            zIndex: 6,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 210,
            top: 25,
            left: 36,
            zIndex: 4,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 248,
            top: 62,
            left: 3,
            zIndex: 8,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 240,
            top: 48,
            left: 65,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 216,
            top: 79,
            left: 65,
            zIndex: 0,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 250,
            top: 2,
            left: 55,
            zIndex: 6,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 240,
            top: 35,
            left: 60,
            zIndex: 3,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 150,
            top: 70,
            left: 10,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 282,
            top: 20,
            left: 0,
            zIndex: 6,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 185,
            top: 0,
            left: 15,
            zIndex: 8,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 206,
            top: 50,
            left: 33,
            zIndex: 8,
        },
         {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 100,
            top: 70,
            left: 80,
            zIndex: 8,
        },
         {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 210,
            top: 5,
            left: 36,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 120,
            top: 80,
            left: 36,
            zIndex: 0,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 121,
            top: 88,
            left: 0,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 256,
            top: 83,
            left: 50,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 174,
            top: 56,
            left: 19,
            zIndex: 0,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 140,
            top: 80,
            left: 11,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 158,
            top: 61,
            left: 34,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 240,
            top: 53,
            left: 14,
            zIndex: 2,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 157,
            top: 97,
            left: 90,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 227,
            top: 21,
            left: 33,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 273,
            top: 53,
            left: 13,
            zIndex: 0,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 294,
            top: 39,
            left: 10,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 166,
            top: 52,
            left: 48,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 192,
            top: 66,
            left: 27,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 132,
            top: 43,
            left: 29,
            zIndex: 2,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 297,
            top: 45,
            left: 38,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 237,
            top: 55,
            left: 53,
            zIndex: 0,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 174,
            top: 60,
            left: 19,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 192,
            top: 37,
            left: 78,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 176,
            top: 75,
            left: 78,
            zIndex: 2,
        },
    ],
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 280,
            top: 61,
            left: 25,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 163,
            top: 86,
            left: 44,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 144,
            top: 21,
            left: 62,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 208,
            top: 53,
            left: 38,
            zIndex: 0,
        },
    ],
]